### ISSUE TITLE
Possible to make those text into internal links?

### ISSUE THREAD

**Issue by Quorafind** [akaalias/obsidian-journey-plugin#2]
When I click the `copy to clipboard`, those jouney text can be transferred into [[]] except tag stuff

**Comment by akaalias** [comment]
Hi @Quorafind – I'm not 100% sure I understand what you mean with "tag stuff."

Can you please show me a current example and what you would expect differently? Thanks!

**Comment by Quorafind** [comment]
hmmmm, like text below is what I generated and copied.
```
## The Journey Between Abstract Generation MOC and Law Resources MOC
- Abstract Generation MOC
- 8a data structure summary
- #pkm
- Law Resources MOC
```
And i hope that I have an option to turn text here into [[]] internal links, like:
```
## The Journey Between Abstract Generation MOC and Law Resources MOC
- [[Abstract Generation MOC]]
- [[8a data structure summary]]
- #pkm
- [[Law Resources MOC]]
```
So that I can use the text to read content in the journey

**Comment by akaalias** [comment]
Got it! Thank you very much - I've added this option to the list of next features.

 I'll close this issue here but make sure to vote on this idea in the forum thread: https://forum.obsidian.md/t/new-plugin-journey-find-the-story-between-your-notes/12153/56
