### ISSUE TITLE
Journey not found when one is present

### ISSUE THREAD

**Issue by ShaneNZ** [akaalias/obsidian-journey-plugin#4]
When trying to find a journey between two notes, one isn't found when it can be seen to exist on the graph:

![image](https://user-images.githubusercontent.com/2524502/107074725-feb55800-684d-11eb-8146-94052d08d3ec.png)

Tags, forward and backlinks are all enabled, taking the scenic route is disabled (so it’s not blocking along the path anywhere). Test vault with no other plugins active and just those six notes shows the same issue (vault sent to you privately).

Obsidian 0.10.12 installer version 0.9.17
v0.0.4 of the plugin
MacOS 11

**Comment by akaalias** [comment]
Hi @ShaneNZ – Regarding 

> via a tag “#nts” - except 04 doesn’t have the #nts tag!

Can you please do a full-text search for #nts? Could it be part of a URL somewhere?

**Comment by akaalias** [comment]
Oh, and one more question: Would you be able/okay to upload the .zip here too for future reference? If not, that's okay too. Just to have everything in one place.

**Comment by ShaneNZ** [comment]
In the test vault, #nts exists in note 03 and 06, but not in note 04. So 03 to 06 should work but doesn't (via tag or links), but 04 to 06 does via the tag? Exists all over the place in my full vault.

Excerpted notes/vault attached.

[Journey Test.zip](https://github.com/akaalias/obsidian-journey-plugin/files/5937531/Journey.Test.zip)

**Comment by akaalias** [comment]
Hi @ShaneNZ – I'm about to do the testing now but I don't see files indexed 01, 02, 03 etc. Can you please clarify which note respond to which index?

**Comment by ShaneNZ** [comment]
> Can you please clarify which note respond to which index?

Oops, sorry gave you the wrong zip file. Try this one:
[journey-test-vault-v2.zip](https://github.com/akaalias/obsidian-journey-plugin/files/5940597/journey-test-vault-v2.zip)

**Comment by ShaneNZ** [comment]
Have just tested this issue with 0.0.5 in both the test vault uploaded above, and in my main vault - in both cases the issue has been resolved.

**Comment by akaalias** [comment]
AMAZING! 🎉 Thank you for helping me figure out how to handle issues like this (forum -> DM -> github issues)
