### ISSUE TITLE
Journey searching endlessly

### ISSUE THREAD

**Issue by KatlarOregon** [akaalias/obsidian-journey-plugin#5]
When I pick two notes, no matter where they are located in my vault, no matter if they are connected, the "Searching..."-window will stay for hours showing no result until I close it manually.
I tried deactivating all other plugins, restarting, reinstalling ... nothing changed.

**Details:**
- Vault size: ~2000 Notes, some not connected or empty
- Windows 10, very strong PC
- Obsidian Sync = enabled
- Obsidian Publish = enabled
- Files are stored locally, not in a cloud.
- Automatic Updates = enabled

If I forgot something, just ask.
Have a good time!
Leo

**Comment by akaalias** [comment]
Hi there! Can you try again with today's update?

**Comment by KatlarOregon** [comment]
Edit:

IT DID IT!

after the second restart of Obsidian it worked!
BIg Thanks!

**Comment by akaalias** [comment]
ZOMG! ZOMG! 🎉 Awesome! Keep me in the loop if it comes up again. Closing this for now :)
