### ISSUE TITLE
mutated vowel/umlaut-tag problems

### ISSUE THREAD

**Issue by KatlarOregon** [akaalias/obsidian-journey-plugin#6]
**The Journey Between Note-Count-Folder/Sonstiges/BIBLIOGRAPHIE/Keller, Gottfried - Gesammelte Briefe 3.1.md and 0204j Biedermeier.md**

- Note-Count-Folder/Sonstiges/BIBLIOGRAPHIE/Keller, Gottfried - Gesammelte Briefe 3.1
- Note-Count-Folder/:brain: Brain/0003 Buchstabengarten
- Note-Count-Folder/:brain: Brain/0001 Bücher
- **#B <–THIS!!**
- 0204l Vormärz
- 0204j Biedermeier

**The tool doesn't recognise a word as a whole tag, if there is a umlaut in it.**
E.g.: #Bücher -> #B

Greetings, Leo

**Comment by akaalias** [comment]
Issue fixed, will be part of the next release within the coming days :)
