### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by phlind** [akaalias/obsidian-journey-plugin#7]
Thanks for the great plugin. Probably this is already know, but the icon keeps dark also in lightmode. Furthermore, the icon in darkmode is brighter than the others:

![Bildschirmfoto 2021-02-08 um 14 28 19](https://user-images.githubusercontent.com/30386310/107226225-1fcaa400-6a1a-11eb-964d-8755b24f5d81.png)
![Bildschirmfoto 2021-02-08 um 14 28 23](https://user-images.githubusercontent.com/30386310/107226227-20fbd100-6a1a-11eb-98b7-eb0d26b32b6f.png)

**Comment by akaalias** [comment]
Thanks for submitting the issue. It's come up by others as well – Will look into it :)

**Comment by akaalias** [comment]
I've started a thread over at https://forum.obsidian.md/t/help-my-plugin-icons-dont-look-right/13179 – Hope someone can point me in the right direction.

**Comment by akaalias** [comment]
Fixed to the best of my abilities in release 0.0.7 (https://github.com/akaalias/obsidian-journey-plugin/releases/tag/0.0.7) 

Please update the plugin to see those changes :)
