### ISSUE TITLE
There seems to be no response after entering Chinese

### ISSUE THREAD

**Issue by ghost** [akaalias/obsidian-journey-plugin#8]
I am very happy to use this plugin.
There seems to be no response after entering Chinese
No note title option appears, I have a lot of notes.
![image](https://user-images.githubusercontent.com/69051504/113328906-76d06380-934f-11eb-973b-e5982deb7944.png)

**Comment by ghost** [comment]
Sorry, it was caused by my incorrect usage.

**Comment by cyandddd** [comment]
how you solved this???
